brew "coreutils"
brew "gnupg"
brew "findutils"
brew "gnu-tar"
brew "tree"
brew "ripgrep"
brew "fzf"
brew "neovim"
brew "spaceship"

cask "ghostty"
cask "visual-studio-code"
cask "whatsapp"
cask "docker"
cask "spotify"